sudo: required

env:
  - DOCKERFILE=Dockerfile
  - DOCKERFILE=Dockerfile-alpine
  - DOCKERFILE=Dockerfile-centos

services:
  - docker

script:
- docker build -t nginxtest -f ${DOCKERFILE} .
- docker run -p 8080:8080 -d nginxtest
- docker run -p 8081:8080 -d --env-file ./.test.env nginxtest
- sleep 5
- curl localhost:8080 | grep "Welcome to nginx!"
- curl localhost:8081 | grep "Welcome to nginx!"
