FROM behance/docker-base:2.6-centos
MAINTAINER Bryan Latten <latten@adobe.com>

ENV CONTAINER_ROLE=web \
    CONTAINER_PORT=8080 \
    CONF_NGINX_SITE="/etc/nginx/sites-available/default" \
    CONF_NGINX_SERVER="/etc/nginx/nginx.conf" \
    NOT_ROOT_USER=nginx

# Using a non-privileged port to prevent having to use setcap internally
EXPOSE ${CONTAINER_PORT}

# - Update security packages, only
RUN /bin/bash -e /security_updates.sh && \
    yum -y -q install epel-release && \
    yum -y -q install nginx && \
    yum -y -q remove epel-release && \
    /bin/bash -e /clean.sh

# Overlay the root filesystem from this repo
COPY ./container/root /

# - Set nginx to listen on defined port
# - NOTE: order of operations is important, new config had to already installed from repo (above)
# - Make temp directory for .nginx runtime files
# - Update nginx.conf user
# - Some operations can be completely removed once this ticket is resolved:
# - https://trac.nginx.org/nginx/ticket/1243
# - Remove older WOFF mime-type
# - Add again with newer mime-type
# - Also add mime-type for WOFF2
RUN sed -i "s/listen [0-9]*;/listen ${CONTAINER_PORT};/" $CONF_NGINX_SITE && \
    mkdir /tmp/.nginx && \
    sed -i "s/^user .*$/user ${NOT_ROOT_USER};/" ${CONF_NGINX_SERVER} && \
    sed -i "/application\/font-woff/d" /etc/nginx/mime.types && \
    sed -i "s/}/\n    font\/woff                             woff;&/" /etc/nginx/mime.types && \
    sed -i "s/}/\n    font\/woff2                            woff2;\n&/g" /etc/nginx/mime.types

RUN goss -g /tests/centos/nginx.goss.yaml validate && \
    /aufs_hack.sh

# NOTE: intentionally NOT using s6 init as the entrypoint
# This would prevent container debugging if any of those service crash
CMD ["/bin/bash", "/run.sh"]
