FROM behance/docker-base:3.0-centos-7

# Use in multi-phase builds, when an init process requests for the container to gracefully exit, so that it may be committed
# Used with alternative CMD (worker.sh), leverages supervisor to maintain long-running processes
ENV CONTAINER_ROLE=web \
    CONTAINER_PORT=8080 \
    CONF_NGINX_SITE="/etc/nginx/sites-available/default" \
    CONF_NGINX_SERVER="/etc/nginx/nginx.conf" \
    NOT_ROOT_USER=nginx \
    S6_KILL_FINISH_MAXTIME=55000

# Using a non-privileged port to prevent having to use setcap internally
EXPOSE ${CONTAINER_PORT}

# - Update security packages, only
RUN /bin/bash -e /security_updates.sh && \
    yum -y -q install epel-release && \
    yum -y -q install nginx ca-certificates && \
    yum -y -q remove epel-release && \
    /bin/bash -e /clean.sh

# Overlay the root filesystem from this repo
COPY --chown=nginx ./container/root /

# - Set nginx to listen on defined port
# - NOTE: order of operations is important, new config had to already installed from repo (above)
# - Make temp directory for .nginx runtime files
# - Update nginx.conf user
# - Set permissions to allow image to be run under a non root user
RUN sed -i "s/listen [0-9]*;/listen ${CONTAINER_PORT};/" $CONF_NGINX_SITE && \
    mkdir /tmp/.nginx && \
    sed -i "s/^user .*$/user ${NOT_ROOT_USER};/" ${CONF_NGINX_SERVER} && \
    /bin/bash -e /scripts/set_permissions.sh

RUN goss -g /tests/centos/nginx.goss.yaml validate && \
    /aufs_hack.sh
